### ISSUE TITLE
Unable to write DI without Simulation ON

### ISSUE THREAD

**Issue by uncommonthinker** [Booozie-Z/Fanuc_GESRTP_Driver#1]
Hey @Booozie-Z 

First of all thanks for this fantastic project. I just came across this, but I sense this might be an excellent push for communication with Fanuc.

I tried reading and writing Data Registers, Data String Registers, and I was able to successfully read and write to the same.

But unfortunately, I am unable to write to DIs/DOs. I am able to successfully read them without issues.

I need to turn the simulation program ON, in the pendant, only after which the values reflect. Am I missing something?

<img width="1680" alt="Screenshot 2023-09-11 at 6 55 08 PM" src="https://github.com/Booozie-Z/Fanuc_GESRTP_Driver/assets/3805632/c6417e00-2323-4c5e-afcd-d149016d1724">

**Comment by uncommonthinker** [comment]
@Booozie-Z @kzelnio-LE 

Need help

**Comment by uncommonthinker** [comment]
**Update:**

I can successfully read and write to DOs, and able to read DIs but able to write to them. I can write only when the simulation is on.

I assume this library is to build an HMI, where HMI cannot write to DIs unless the bit simulation is turned on. However, I need to know if I could communicate directly without the simulation being turned on.

Appreciate any input.

**Comment by Booozie-Z** [comment]
This is most likely a robot configuration issue. Where are your DIs confgured to?

**Comment by uncommonthinker** [comment]
The ones i am trying to write are configured to ethernet/ip (Rack - 89) from addresses 129 - 192.

**Comment by Booozie-Z** [comment]
That is why. Your ethernet device is controlling those addresses. The ethernet device is resetting the DI as soon as you write.

Try configuring a new set of DIs to something in the robot's memory. I.E. Rack 0 Slot 0 Start 100.

**Comment by uncommonthinker** [comment]
Ok. Will try and use the 0,0 configuration and update you on the same.

Thanks

**Comment by uncommonthinker** [comment]
Hey Kyle,

Thanks a ton. Was able to configure and write to DIs. You are awesome. Hoping to creating a library around your source and contributing back to the community.
